In [1]:
import numpy as np
import pandas as pd
import warnings
from sklearn.model_selection import train_test_split

from mypipes_property import *

warnings.filterwarnings('ignore')

In [2]:
df = pd.read_csv(r'/home/siddarth.jha@npci.org.in/Documents/Training/Data/Property_train.csv')

In [3]:
df.head()

,Junk,InteriorsStyle,PriceIndex8,ListDate,Material,PriceIndex9,Agency,AreaIncomeType,EnvRating,PriceIndex7,...,Region,PriceIndex5,SubModel,Facade,State,NormalisedPopulation,BuildYear,RegionType,PropertyAge,PriceIndex2
0,0,6LLJ,14674.0,9/7/2010,UT7W,8270,CAT3,B,missing,13143.0,...,A,9022.0,6E9G,GREEN,MD,42077,2008,A,2,10692.0
1,1,XZ9F,4172.0,1/7/2009,PRN0,3890,CAT2,B,missing,3461.0,...,A,2742.0,FIVQ,SILVER,OK,77258,2002,A,7,3615.0
2,0,QWEV,8210.0,6/23/2010,A9RA,5900,CAT1,B,missing,6922.0,...,A,3768.0,4K0H,SILVER,SC,94514,2004,A,6,5805.0
3,0,MK2K,7309.0,3/19/2009,RRJQ,7460,OTHER,A,missing,6300.0,...,A,5370.0,ZLXY,WHITE,NC,82302,2002,C,7,6444.0
4,0,GK4G,9182.0,3/3/2010,HE5A,6400,OTHER,B,missing,8330.0,...,A,4803.0,FIVQ,SILVER,SC,49176,2007,B,3,6286.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 62035 entries, 0 to 62034
Data columns (total 31 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Junk                   62035 non-null  int64
 1   InteriorsStyle         62035 non-null  object
 2   PriceIndex8            62035 non-null  object
 3   ListDate               62035 non-null  object
 4   Material               62035 non-null  object
 5   PriceIndex9            62035 non-null  int64
 6   Agency                 62035 non-null  object
 7   AreaIncomeType         62035 non-null  object
 8   EnvRating              62035 non-null  object
 9   PriceIndex7            62035 non-null  object
 10  ExpeditedListing       62035 non-null  int64
 11  PriceIndex4            62035 non-null  object
 12  PriceIndex1            62035 non-null  object
 13  PriceIndex6            62035 non-null  object
 14  PRIMEUNIT              62035 non-null  object
 15  Channel                62035 non-null  object
 16  Zip                    62035 non-null  int64
 17  InsurancePremiumIndex  62035 non-null  int64
 18  PlotType               62035 non-null  object
 19  Architecture           62035 non-null  object
 20  PriceIndex3            62035 non-null  object
 21  Region                 62035 non-null  object
 22  PriceIndex5            62035 non-null  object
 23  SubModel               62035 non-null  object
 24  Facade                 62035 non-null  object
 25  State                  62035 non-null  object
 26  NormalisedPopulation   62035 non-null  int64
 27  BuildYear              62035 non-null  int64
 28  RegionType             62035 non-null  object
 29  PropertyAge            62035 non-null  int64
 30  PriceIndex2            62035 non-null  object
dtypes: int64(8), object(23)
memory usage: 14.7+ MB

In [5]:
df['ListDate'].value_counts()

11/23/2010    329
2/25/2009     325
11/3/2010     315
12/8/2010     312
10/13/2010    311
             ...
5/25/2009       2
2/20/2010       2
1/9/2009        2
12/24/2010      1
1/10/2010       1
Name: ListDate, Length: 516, dtype: int64

In [6]:
'''
InteriorsStyle :DROP
P1:
Junk, PriceIndex9, ExpeditedListing, Zip, InsurancePremiumIndex, NormalisedPopulation, BuildYear,
    PropertyAge: Impute missing values

P2:
PriceIndex8,  PriceIndex7, PriceIndex4, PriceIndex1, PriceIndex6, PriceIndex3, 
    PriceIndex5, PriceIndex2, : Impute Missning & Convert to numeric

P3:
EnvRating, Material, Agency, AreaIncomeType, Channel, PlotType, Architecture, Region, SubModel, Facade, State, 
    RegionType, PRIMEUNIT: impute missing, create dummy, 


P4 & 5:
ListDate : date type
'''

'\nInteriorsStyle :DROP\nP1:\nJunk, PriceIndex9, ExpeditedListing, Zip, InsurancePremiumIndex, NormalisedPopulation, BuildYear,\n    PropertyAge: Impute missing values\n\nP2:\nPriceIndex8,  PriceIndex7, PriceIndex4, PriceIndex1, PriceIndex6, PriceIndex3, \n    PriceIndex5, PriceIndex2, : Impute Missning & Convert to numeric\n\nP3:\nEnvRating, Material, Agency, AreaIncomeType, Channel, PlotType, Architecture, Region, SubModel, Facade, State, \n    RegionType, PRIMEUNIT: impute missing, create dummy, \n\n\nP4 & 5:\nListDate : date type\n'

In [7]:
X_train, X_test = train_test_split(df, test_size = 0.2, random_state = 42)

In [8]:
X_train

,Junk,InteriorsStyle,PriceIndex8,ListDate,Material,PriceIndex9,Agency,AreaIncomeType,EnvRating,PriceIndex7,...,Region,PriceIndex5,SubModel,Facade,State,NormalisedPopulation,BuildYear,RegionType,PropertyAge,PriceIndex2
13458,0,6UCD,12526.0,11/13/2009,ZCI3,8105,CAT2,B,missing,11713.0,...,A,8018.0,FIVQ,SILVER,TN,42717,2008,A,1,8657.0
40671,1,X07E,19071.0,4/8/2010,JD5J,10185,CAT2,A,missing,16300.0,...,A,12221.0,7529,BLACK,CO,94947,2006,A,4,14776.0
2061,0,RELA,6080.0,3/4/2009,5GAZ,4160,CAT1,B,missing,4720.0,...,A,3907.0,ONP1,RED,AZ,82530,2004,A,5,4457.0
1870,0,98SV,12752.0,11/18/2009,RRJQ,9700,OTHER,A,missing,11510.0,...,A,7914.0,6G22,SILVER,SC,73722,2004,C,5,9128.0
11917,0,K3BB,10110.0,8/5/2010,4ZHP,4785,CAT2,B,missing,8369.0,...,A,4715.0,M81Y,BLACK,OK,68313,2006,A,4,6022.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54343,1,VQNR,4311.0,9/17/2009,ZCI3,2570,CAT3,missing,missing,3252.0,...,A,2548.0,UA42,GREEN,NC,92504,2003,A,6,3443.0
38158,0,OR99,10896.0,2/20/2009,9TQI,9475,CAT1,A,missing,8946.0,...,A,7820.0,8UTN,BLACK,CA,81484,2003,A,6,7745.0
860,0,V3Y1,9412.0,3/4/2009,NYFD,6230,CAT2,A,missing,7748.0,...,A,6711.0,QW88,SILVER,CA,69249,2005,A,4,7935.0
15795,1,7KCI,10515.0,7/22/2009,C8A4,5870,CAT1,B,missing,8774.0,...,A,7661.0,BNAA,GOLD,TN,90061,2006,A,3,11066.0
56422,0,ISY8,7860.0,1/19/2010,ZCI3,4565,CAT2,B,missing,6622.0,...,A,3656.0,FIVQ,SILVER,TX,68202,2005,A,5,3600.0

In [9]:
p1 = pdPipeline([
    ('var_select', VarSelector(['Junk', 'PriceIndex9', 'ExpeditedListing', 'Zip', 'InsurancePremiumIndex', 
                                'NormalisedPopulation', 'BuildYear', 'PropertyAge'])),
    ('missing_trt', MissingValues())
])

p2 = pdPipeline([
    ('var_select', VarSelector(['PriceIndex1', 'PriceIndex2', 'PriceIndex3', 'PriceIndex4', 'PriceIndex5', 
                                'PriceIndex6', 'PriceIndex7', 'PriceIndex8'])),   
    ('convert_to_num', convert_to_numeric()),
    ('missing_trt', MissingValues())
    
])

p3 = pdPipeline([
    ('var_select', VarSelector(['EnvRating', 'Material', 'Agency', 'AreaIncomeType', 'Channel', 'PlotType','Architecture'
                                           , 'Region', 'SubModel', 'Facade', 'State', 'RegionType', 'PRIMEUNIT'])),
    ('missing_trt', MissingValues()),
    ('create_dummy', convert_to_dummy(6000))
])

p4 = pdPipeline([
    ('var_select', VarSelector(['ListDate'])),
    ('dt_cyclic', cyclic_features())
])

p5 = pdPipeline([
    ('var_select', VarSelector(['ListDate'])),
    ('dt', datetime_conversion())
])

data_pipe = FeatureUnion([
    ('missing_num', p1),
    ('obj_to_num', p2),
    ('obj_to_dum', p3),
    ('dt_to_cyclic', p4),
    ('dt_to_conv', p5)
])

In [10]:
data_pipe.fit(X_train)

FeatureUnion(transformer_list=[('missing_num',
                                pdPipeline(steps=[('var_select',
                                                   VarSelector(feature_names=['Junk',
                                                                              'PriceIndex9',
                                                                              'ExpeditedListing',
                                                                              'Zip',
                                                                              'InsurancePremiumIndex',
                                                                              'NormalisedPopulation',
                                                                              'BuildYear',
                                                                              'PropertyAge'])),
                                                  ('missing_trt',
                                                   MissingValues())])),
                               ('obj_to_num',
                                pdPipeline(steps=[('var_select',
                                                   VarSelector(feature_names=['PriceIndex1',
                                                                              '...
                                                                              'RegionType',
                                                                              'PRIMEUNIT'])),
                                                  ('missing_trt',
                                                   MissingValues()),
                                                  ('create_dummy',
                                                   convert_to_dummy(freq_cutoff=6000))])),
                               ('dt_to_cyclic',
                                pdPipeline(steps=[('var_select',
                                                   VarSelector(feature_names=['ListDate'])),
                                                  ('dt_cyclic',
                                                   cyclic_features())])),
                               ('dt_to_conv',
                                pdPipeline(steps=[('var_select',
                                                   VarSelector(feature_names=['ListDate'])),
                                                  ('dt',
                                                   datetime_conversion())]))])

In [11]:
len(data_pipe.get_feature_names())

53

In [12]:
x_train = pd.DataFrame(data=data_pipe.transform(X_train),
                    columns=data_pipe.get_feature_names())
x_test=pd.DataFrame(data=data_pipe.transform(X_test),
                    columns=data_pipe.get_feature_names())

In [14]:
x_train

,missing_num__Junk,missing_num__PriceIndex9,missing_num__ExpeditedListing,missing_num__Zip,missing_num__InsurancePremiumIndex,missing_num__NormalisedPopulation,missing_num__BuildYear,missing_num__PropertyAge,obj_to_num__PriceIndex1,obj_to_num__PriceIndex2,...,obj_to_dum__PRIMEUNIT_missing,dt_to_cyclic__ListDate_weekday_sin,dt_to_cyclic__ListDate_weekday_cos,dt_to_cyclic__ListDate_month_sin,dt_to_cyclic__ListDate_month_cos,dt_to_cyclic__ListDate_day_sin,dt_to_cyclic__ListDate_day_cos,dt_to_conv__ListDate_weekday,dt_to_conv__ListDate_month,dt_to_conv__ListDate_day
0,0.0,8105.0,0.0,37771.0,834.0,42717.0,2008.0,1.0,7785.0,8657.0,...,1.0,-0.433884,-0.900969,-0.500000,8.660254e-01,0.485302,-0.874347,4.0,11.0,13.0
1,1.0,10185.0,0.0,80229.0,2206.0,94947.0,2006.0,4.0,13261.0,14776.0,...,1.0,0.433884,-0.900969,0.866025,-5.000000e-01,0.998717,-0.050649,3.0,4.0,8.0
2,0.0,4160.0,0.0,85009.0,1243.0,82530.0,2004.0,5.0,3521.0,4457.0,...,1.0,0.974928,-0.222521,1.000000,6.123234e-17,0.724793,0.688967,2.0,3.0,4.0
3,0.0,9700.0,0.0,29697.0,569.0,73722.0,2004.0,5.0,7880.0,9128.0,...,1.0,0.974928,-0.222521,-0.500000,8.660254e-01,-0.485302,-0.874347,2.0,11.0,18.0
4,0.0,4785.0,0.0,73108.0,1215.0,68313.0,2006.0,4.0,5039.0,6022.0,...,1.0,0.433884,-0.900969,-0.866025,-5.000000e-01,0.848644,0.528964,3.0,8.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49623,1.0,2570.0,0.0,28273.0,1641.0,92504.0,2003.0,6.0,2449.0,3443.0,...,1.0,0.433884,-0.900969,-1.000000,-1.836970e-16,-0.299363,-0.954139,3.0,9.0,17.0
49624,0.0,9475.0,0.0,91752.0,2063.0,81484.0,2003.0,6.0,6267.0,7745.0,...,1.0,-0.433884,-0.900969,0.866025,5.000000e-01,-0.790776,-0.612106,4.0,2.0,20.0
49625,0.0,6230.0,0.0,92057.0,1411.0,69249.0,2005.0,4.0,6337.0,7935.0,...,1.0,0.974928,-0.222521,1.000000,6.123234e-17,0.724793,0.688967,2.0,3.0,4.0
49626,1.0,5870.0,0.0,37122.0,2495.0,90061.0,2006.0,3.0,8671.0,11066.0,...,1.0,0.974928,-0.222521,-0.500000,-8.660254e-01,-0.968077,-0.250653,2.0,7.0,22.0
49627,0.0,4565.0,0.0,77041.0,630.0,68202.0,2005.0,5.0,2777.0,3600.0,...,1.0,0.781831,0.623490,0.500000,8.660254e-01,-0.651372,-0.758758,1.0,1.0,19.0

In [15]:
x_test

,missing_num__Junk,missing_num__PriceIndex9,missing_num__ExpeditedListing,missing_num__Zip,missing_num__InsurancePremiumIndex,missing_num__NormalisedPopulation,missing_num__BuildYear,missing_num__PropertyAge,obj_to_num__PriceIndex1,obj_to_num__PriceIndex2,...,obj_to_dum__PRIMEUNIT_missing,dt_to_cyclic__ListDate_weekday_sin,dt_to_cyclic__ListDate_weekday_cos,dt_to_cyclic__ListDate_month_sin,dt_to_cyclic__ListDate_month_cos,dt_to_cyclic__ListDate_day_sin,dt_to_cyclic__ListDate_day_cos,dt_to_conv__ListDate_weekday,dt_to_conv__ListDate_month,dt_to_conv__ListDate_day
0,0.0,7580.0,0.0,32824.0,1974.0,71393.0,2006.0,4.0,7438.0,8736.0,...,1.0,0.974928,-0.222521,1.000000e+00,6.123234e-17,-2.449294e-16,1.000000,2.0,3.0,31.0
1,0.0,4160.0,0.0,85009.0,1543.0,85810.0,2003.0,6.0,2878.0,3655.0,...,1.0,0.974928,-0.222521,1.000000e+00,6.123234e-17,-9.377521e-01,0.347305,2.0,3.0,25.0
2,0.0,8300.0,0.0,74135.0,834.0,44711.0,2008.0,1.0,8258.0,9007.0,...,1.0,-0.433884,-0.900969,-8.660254e-01,-5.000000e-01,-8.978045e-01,-0.440394,4.0,8.0,21.0
3,0.0,6240.0,0.0,22801.0,2152.0,83546.0,2005.0,5.0,5286.0,6589.0,...,1.0,0.974928,-0.222521,8.660254e-01,5.000000e-01,-9.884683e-01,0.151428,2.0,2.0,24.0
4,0.0,10590.0,0.0,80022.0,728.0,68287.0,2004.0,5.0,8522.0,9747.0,...,1.0,0.781831,0.623490,-8.660254e-01,-5.000000e-01,-4.853020e-01,-0.874347,1.0,8.0,18.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12402,0.0,9465.0,0.0,33619.0,671.0,53218.0,2006.0,3.0,10789.0,12483.0,...,1.0,0.433884,-0.900969,-8.660254e-01,-5.000000e-01,-7.247928e-01,0.688967,3.0,8.0,27.0
12403,1.0,4765.0,0.0,80229.0,909.0,92287.0,2004.0,6.0,0.0,0.0,...,1.0,0.433884,-0.900969,1.000000e+00,6.123234e-17,-4.853020e-01,-0.874347,3.0,3.0,18.0
12404,1.0,7800.0,0.0,74135.0,920.0,50051.0,2008.0,1.0,8194.0,9045.0,...,1.0,0.974928,-0.222521,-5.000000e-01,-8.660254e-01,-9.680771e-01,-0.250653,2.0,7.0,22.0
12405,1.0,4910.0,0.0,76040.0,1966.0,56381.0,2002.0,8.0,2294.0,3354.0,...,1.0,0.433884,-0.900969,-2.449294e-16,1.000000e+00,-1.011683e-01,-0.994869,3.0,12.0,16.0
12406,1.0,4200.0,0.0,80817.0,1918.0,93882.0,2004.0,5.0,5674.0,7029.0,...,1.0,0.433884,-0.900969,8.660254e-01,-5.000000e-01,9.680771e-01,-0.250653,3.0,4.0,9.0

In [17]:
x_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49628 entries, 0 to 49627
Data columns (total 53 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   missing_num__Junk                   49628 non-null  float64
 1   missing_num__PriceIndex9            49628 non-null  float64
 2   missing_num__ExpeditedListing       49628 non-null  float64
 3   missing_num__Zip                    49628 non-null  float64
 4   missing_num__InsurancePremiumIndex  49628 non-null  float64
 5   missing_num__NormalisedPopulation   49628 non-null  float64
 6   missing_num__BuildYear              49628 non-null  float64
 7   missing_num__PropertyAge            49628 non-null  float64
 8   obj_to_num__PriceIndex1             49628 non-null  float64
 9   obj_to_num__PriceIndex2             49628 non-null  float64
 10  obj_to_num__PriceIndex3             49628 non-null  float64
 11  obj_to_num__PriceIndex4             49628 non-null  float64
 12  obj_to_num__PriceIndex5             49628 non-null  float64
 13  obj_to_num__PriceIndex6             49628 non-null  float64
 14  obj_to_num__PriceIndex7             49628 non-null  float64
 15  obj_to_num__PriceIndex8             49628 non-null  float64
 16  obj_to_dum__EnvRating_missing       49628 non-null  float64
 17  obj_to_dum__Material_PRN0           49628 non-null  float64
 18  obj_to_dum__Material_C8A4           49628 non-null  float64
 19  obj_to_dum__Material_ZCI3           49628 non-null  float64
 20  obj_to_dum__Agency_CAT1             49628 non-null  float64
 21  obj_to_dum__Agency_CAT2             49628 non-null  float64
 22  obj_to_dum__Agency_CAT3             49628 non-null  float64
 23  obj_to_dum__Agency_OTHER            49628 non-null  float64
 24  obj_to_dum__AreaIncomeType_A        49628 non-null  float64
 25  obj_to_dum__AreaIncomeType_B        49628 non-null  float64
 26  obj_to_dum__Channel_Direct          49628 non-null  float64
 27  obj_to_dum__Channel_Other           49628 non-null  float64
 28  obj_to_dum__Channel_Agent           49628 non-null  float64
 29  obj_to_dum__PlotType_WHBI           49628 non-null  float64
 30  obj_to_dum__PlotType_W62B           49628 non-null  float64
 31  obj_to_dum__Architecture_YIK5       49628 non-null  float64
 32  obj_to_dum__Architecture_TP7R       49628 non-null  float64
 33  obj_to_dum__Architecture_I3Z9       49628 non-null  float64
 34  obj_to_dum__Architecture_AVYP       49628 non-null  float64
 35  obj_to_dum__Region_A                49628 non-null  float64
 36  obj_to_dum__SubModel_FIVQ           49628 non-null  float64
 37  obj_to_dum__Facade_SILVER           49628 non-null  float64
 38  obj_to_dum__Facade_WHITE            49628 non-null  float64
 39  obj_to_dum__Facade_BLUE             49628 non-null  float64
 40  obj_to_dum__State_TX                49628 non-null  float64
 41  obj_to_dum__State_FL                49628 non-null  float64
 42  obj_to_dum__RegionType_A            49628 non-null  float64
 43  obj_to_dum__PRIMEUNIT_missing       49628 non-null  float64
 44  dt_to_cyclic__ListDate_weekday_sin  49628 non-null  float64
 45  dt_to_cyclic__ListDate_weekday_cos  49628 non-null  float64
 46  dt_to_cyclic__ListDate_month_sin    49628 non-null  float64
 47  dt_to_cyclic__ListDate_month_cos    49628 non-null  float64
 48  dt_to_cyclic__ListDate_day_sin      49628 non-null  float64
 49  dt_to_cyclic__ListDate_day_cos      49628 non-null  float64
 50  dt_to_conv__ListDate_weekday        49628 non-null  float64
 51  dt_to_conv__ListDate_month          49628 non-null  float64
 52  dt_to_conv__ListDate_day            49628 non-null  float64
dtypes: float64(53)
memory usage: 20.1 MB